### ISSUE TITLE
`npm install` fails on first time setup.

### ISSUE THREAD

**Issue by akath20** [medooze/test-server#3]
After cloning the repo I tried to run `npm install` and it looks to be compiling c++ code unsuccessfully. 

This could be an issue with node-gyp, but it says it's failing in the medooze-media-server.

<img width="1108" alt="image" src="https://user-images.githubusercontent.com/6372519/53033168-4c4c1680-3425-11e9-98e9-1e70ba618605.png">

**Comment by murillo128** [comment]
Could you paste the errors before the screenshoot?

**Comment by akath20** [comment]
Here is the full output of `npm install`
[output.txt](https://github.com/medooze/test-server/files/2881108/output.txt)

**Comment by murillo128** [comment]
```
aligned deallocation function of type 'void (void *, enum std::align_val_t) noexcept' is only available on macOS 10.13 or newer
```
Could this be the problem?

**Comment by akath20** [comment]
I did see that, I am on 10.14.

**Comment by murillo128** [comment]
I have a problem with the xcode on my mac min, so I can`t confirm if I can reproduce it locally, but definitively that error is causing the compilation to fail (not sure about the root cause yet).

**Comment by murillo128** [comment]
I have solved the problems on my mac mini and I cannot reproduce the problem locally.. :(

**Comment by murillo128** [comment]
Could you try to clone the https://github.com/medooze/media-server-node directly, remove the `-faligned-new` in [`binding.gyp`](https://github.com/medooze/media-server-node/blob/master/binding.gyp#L28)  and try to compile it with:
```
npm i
```

**Comment by akath20** [comment]
Still no luck.

<img width="1074" alt="image" src="https://user-images.githubusercontent.com/6372519/53110879-ce554180-34f0-11e9-87f1-f5ebca215a9d.png">

**Comment by murillo128** [comment]
You need to fetch git submodules as well, i think it is:
```
git submodule update --init --recursive
```

**Comment by akath20** [comment]
Still no luck.

Submodule 'external/mp4v2/lib' (https://github.com/medooze/mp4v2.git) registered for path 'external/mp4v2/lib'
Submodule 'external/srtp/lib' (https://github.com/cisco/libsrtp.git) registered for path 'external/srtp/lib'
Submodule 'media-server' (https://github.com/medooze/media-server.git) registered for path 'media-server'
Cloning into '/Users/alex/Documents/WebRTC/test-server/media-server-node/external/mp4v2/lib'...
Cloning into '/Users/alex/Documents/WebRTC/test-server/media-server-node/external/srtp/lib'...
Cloning into '/Users/alex/Documents/WebRTC/test-server/media-server-node/media-server'...
Submodule path 'external/mp4v2/lib': checked out 'e2822f28cc74957573a71cc7e2c26ce7e7867e66'
Submodule path 'external/srtp/lib': checked out '541c8585bfd0a2cf70225b9bc7826ee0ffef0d43'
Submodule path 'media-server': checked out '38fd267c768a7e2bc1dbfe434c6407815f6094e6'
Submodule 'ext/libdatachannels' (https://github.com/medooze/libdatachannels.git) registered for path 'media-server/ext/libdatachannels'
Cloning into '/Users/alex/Documents/WebRTC/test-server/media-server-node/media-server/ext/libdatachannels'...
Submodule path 'media-server/ext/libdatachannels': checked out '4d008acdea3b7fe2bfc8e86904dc3b76b9123467'


[output.txt](https://github.com/medooze/test-server/files/2885805/output.txt)

**Comment by akath20** [comment]
@murillo128 maybe we can work on a common ground. 
With docker installed:

`docker run -it node:8 /bin/bash`

I cloned this repo and ran `npm install` and had the same issue.

**Comment by josemrecio** [comment]
By default debian 9 ships with gcc-6, you need gcc-7 or gcc-8.
I have successfully built in debian 9 following these steps:

```
# add the following line to /etc/apt/sources.list
#deb http://deb.debian.org/debian testing main
sudo apt update
sudo apt upgrade
# cleanup
sudo apt --purge autoremove

# install build tools
sudo apt-get -y install git build-essential
# check gcc version, it should be version 8
#gcc --version
#g++ --version

# install nvm and node
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
# logout and login again
nvm install 9.11.2
# check version
node --version

git clone --recursive https://github.com/medooze/test-server
cd test-server
npm install
```

**Comment by murillo128** [comment]
I have also published a new version of the media-server removing the aligned new for macOS to see if it solves the original problem.

**Comment by akath20** [comment]
I am trying those steps against debian now. I tried it against a ubuntu vm and didn't have luck... That would also need to work for my setup, but for now let me try debian.

**Comment by akath20** [comment]
Got this to work, just for reference of what it was on Ubuntu:

replace 
```
```
```
add-apt-repository ppa:ubuntu-toolchain-r/test


```
